### PR TITLE
Change ipdb ref to test bigchaindb

### PR DESCRIPTION
**Pull request by future-is-present**
Since IPDB is coming to the end, I have updated the references to testnet.bigchaindb.com

### CODE REVIEW

**Comment by ttmc** [comment]
In the content of the first page (currently hosted at https://tutorials.bigchaindb.com/crab/ ), there's the line, "In the example given below, we connect to the IPDB network where we already created account and received credentials." That line (and others like it) will also have to be updated, but I'm not sure where the source for that line _is_. Apparently it's not in this repo.

**Comment by future-is-present** [comment]
@ttmc that line is already changed in the first commit, and yes is in this repo, check `src/app/components/Home.jsx`

**Review by jernejpregelj — APPROVED** [review]

**Review by ttmc — APPROVED** [review]
@manolodewiner Somehow I missed that. Doh!

**Comment by ttmc** [comment]
@manolodewiner I see that you merged this PR but the live page at https://tutorials.bigchaindb.com/crab/ is still showing IPDB. I think there's something wrong with the deployment tooling. Matthias may know more. He gets back next week.

**Pull request merged**
